# -*- coding: utf-8 -*-
"""Q10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMkVQghTKATzzTJ_gXU9wAA5pfkeNjlx
"""

a = input("Enter a sentence: ")

b = a.split()
r = ' '.join(reversed(b))

print("Reversed Sentence:", r)

