# -*- coding: utf-8 -*-
"""Q12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMkVQghTKATzzTJ_gXU9wAA5pfkeNjlx
"""



a = int(input("Enter the Number "))

b = 0
while a>0:
  c = a%10
  b = (b*10)+c
  a //= 10
print(b)