# -*- coding: utf-8 -*-
"""Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMkVQghTKATzzTJ_gXU9wAA5pfkeNjlx
"""

a = input("Enter the string")
digits = 0
letters = 0
for char in a:
    if char.isdigit():
        digits = digits+1
    elif char.isalpha():
        letters = letters+1

print("Numbers of digit:", digits)
print("Numbers of letters:", letters)