# -*- coding: utf-8 -*-
"""Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMkVQghTKATzzTJ_gXU9wAA5pfkeNjlx
"""

Physics = float(input("Enter the Physics marks"))
Chemistry = float(input("Enter the Chemistry marks"))
Biology = float(input("Enter the Biology marks"))
Mathematics = float(input("Enter the Mathematics marks"))
Computer = float(input("Enter the Computer marks"))

Total_marks = Physics+Chemistry+Biology+Mathematics+Computer
percentage = (Total_marks/500)*100

if percentage >= 90:
    grade = 'A'
elif 80 <= percentage < 90:
    grade = 'B'
elif 70 <= percentage < 80:
    grade = 'C'
elif 60 <= percentage < 70:
    grade = 'D'
elif 40 <= percentage < 60:
    grade = 'E'
else:
    grade = 'F'


print("Grade =", grade)
