# -*- coding: utf-8 -*-
"""Q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMkVQghTKATzzTJ_gXU9wAA5pfkeNjlx
"""

a = int(input("Enter a number"))
factorial = 1
for i in range(2, a + 1):
    factorial *= i
print(factorial)