# -*- coding: utf-8 -*-
"""Q6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMkVQghTKATzzTJ_gXU9wAA5pfkeNjlx
"""

a = int(input("Enter the Number"))
if a<=0:
  print("Invalid Number")
b = 0
for i in range(1,a):
  if a%i == 0:
    b = i+b
print(a,b)
if b==a:
  print("yes")
else:
  print("no")

