# -*- coding: utf-8 -*-
"""Q7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMkVQghTKATzzTJ_gXU9wAA5pfkeNjlx
"""

string1 = input("Enter the first string: ").lower()
string2 = input("Enter the second string: ").lower()

if sorted(string1) == sorted(string2):
    print("True")
else:
    print("False")

