# -*- coding: utf-8 -*-
"""Q8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMkVQghTKATzzTJ_gXU9wAA5pfkeNjlx
"""

num1 = int(input("Enter the first number"))
num2 = int(input("Enter the second number"))

a = num1 if num1> num2 else num2
while True:
    if a % num1 == 0 and a % num2 == 0:
        lcm = a
        break
    a += 1
print(lcm)

